import { createSlice } from "@reduxjs/toolkit";

// Defining Slice for ID
const userId = createSlice({
    name: "userId",
    initialState: { value:'' },
    reducers: {
        setUserIdInStore: (state, action) => {
            state.value = action.payload;
        },
    },
})

// Export the actions generated by createSlice
export const { setUserIdInStore } = userId.actions;

export default userId.reducer;