'use client'

import { createSlice, createAsyncThunk, PayloadAction } from '@reduxjs/toolkit';
import axios from 'axios';
import { useSelector } from 'react-redux';

// Defining Model for lead slicing
interface Lead {
    Name: string
    Id: string;
    Company: string;
    Title: string;
    Email: string;
    Phone_Number: string;
    Address: string;
};
interface LeadsState {
    leads: Lead[],
    status: 'idle' | 'loading' |'succeeded' | 'failed',
    error: string | null,
};
// Initial State
const initialState : LeadsState = {
    leads: [],
    status: 'idle',
    error: null,
};

const id = useSelector((state:any) => state.id.leads);
const user_id = id["id"];

const fetchLeads = createAsyncThunk('leads/fetchLeads', async() => {
    const response = await axios.get(`/api/getLeads?id=${user_id}`);
    return response.data;
})

const leadsSlice = createSlice({ 
    name: 'leads',
    initialState,
    reducers: {
        // Action to store the leads in the Redux store
        setLeadsInStore: (state, action: PayloadAction<Lead[]>) => {
          state.leads = action.payload;
        },
    },
    extraReducers: (builder) => {
        builder
       .addCase(fetchLeads.pending, (state) => { state.status = 'loading'; })
       .addCase(fetchLeads.fulfilled, (state, action) => {
        state.status = 'succeeded';
        state.leads = action.payload;
      })
      .addCase(fetchLeads.rejected, (state: LeadsState, action) => {
        state.status = 'failed';
        state.error = action.error.message!;
      });
  },
});

// Export the actions generated by createSlice
export const { setLeadsInStore } = leadsSlice.actions;

export default leadsSlice.reducer;
